wandb_version: 1

learning_rate:
  desc: null
  value: 4.0e-06
batch_size:
  desc: null
  value: 8000
architecture:
  desc: null
  value: z2nice
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.10
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1697708029.753402
    t:
      1:
      - 1
      - 9
      - 41
      - 55
      - 103
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.10
      8:
      - 2
      - 5
